version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
      - "48400:48400"
      - "5502:5502"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    restart: unless-stopped